<?php
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for filter items block
 *
 * @var \Magento\LayeredNavigation\Block\Navigation\FilterRenderer $block
 * @var \IntegerNet\Solr\Model\Search\Adapter\FilterItem[] $filterItems
 */
?>
<?php $filterItem = current($filterItems) ?>
<?php if ($filterItem->canUsePriceSlider()): ?>
    <?php $currencySymbol = $filterItem->getCurrencySymbol() ?>
    <span class="filter-value">
        <?php echo $filterItem->getSelectedMinValueFormatted() ?>
        -
        <?php echo $filterItem->getSelectedMaxValueFormatted() ?>
    </span>
    <br><br>
    <div class="ui-slider-wrapper">
        <div class="filter-options-slider"></div>
    </div>

    <script>
        require([
            'jquery',
            'jquery/ui',
            'jQueryUiSlider',
            'Magento_Catalog/js/price-utils'
        ], function ($, _ui, slider, priceUtils) {

            var valueContainer = $('.filter-value');

            $('.filter-options-slider').slider({
                range: true,
                min: <?php echo $filterItem->getMinAvailableValue() ?>,
                max: <?php echo $filterItem->getMaxAvailableValue() ?>,
                values: [<?php echo $filterItem->getSelectedMinValue() ?>, <?php echo $filterItem->getSelectedMaxValue() ?>],
                slide: function (event, ui) {
                    var newValue = priceUtils.formatPrice(ui.values[0])
                        + ' <?php echo $currencySymbol ?> - '
                        + priceUtils.formatPrice(ui.values[1])
                        + ' <?php echo $currencySymbol ?>';

                    valueContainer.html(newValue);
                }
            });
        });
    </script>
<?php else: ?>
    <ol class="items">
        <?php foreach ($filterItems as $filterItem): ?>
            <li class="item">
                <?php if ($filterItem->getCount() > 0): ?>
                    <?php if ($filterItem->getName() === '_Price'): ?>
                        <div class="filter-options-slider"></div>
                    <?php else: ?>
                        <a class="filter-options-link" href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
                            <label class="tickbox<?php if ($filterItem->isActive()): ?> tickbox--active<?php endif ?>"
                                   for="">
                                <input class="tickbox__field" type="checkbox">
                            </label>
                            <?php /* @escapeNotVerified */
                            echo $filterItem->getLabel() ?>
                            <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                                <span class="count"><?php /* @escapeNotVerified */
                                    echo $filterItem->getCount() ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1): ?><?php /* @escapeNotVerified */
                                echo __('item') ?><?php else: ?><?php /* @escapeNotVerified */
                                echo __('items') ?><?php endif; ?></span></span>
                            <?php endif; ?>
                        </a>
                    <?php endif; ?>

                <?php else: ?>
                    <?php /* @escapeNotVerified */
                    echo $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php /* @escapeNotVerified */
                            echo $filterItem->getCount() ?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1): ?><?php /* @escapeNotVerified */
                            echo __('item') ?><?php else: ?><?php /* @escapeNotVerified */
                            echo __('items') ?><?php endif; ?></span></span>
                    <?php endif; ?>
                <?php endif; ?>
            </li>
        <?php endforeach ?>
    </ol>

    <script type="custom">
    jQuery(document).ready(function(){
        var filter = jQuery('.filter-options-link');

        filter.each(function(){
            var element = jQuery(this);
            var tickbox = element.find('.tickbox');

            element.click(function(){
                tickbox.toggleClass('tickbox--active');
            })
        })
    })

    </script>
<?php endif; ?>
