<?php
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for filter items block
 *
 * @var \Magento\LayeredNavigation\Block\Navigation\FilterRenderer $block
 * @var \IntegerNet\Solr\Model\Search\Adapter\FilterItem[] $filterItems
 */
?>

<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a class="filter-options-link"
                   href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>"
                   data-mage-init='{"filterOptionsLink":{}}'>
                    <label class="tickbox<?php if ($filterItem->isActive()): ?> tickbox--active<?php endif ?>" for="">
                        <input class="tickbox__field" type="checkbox" >
                    </label>
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?php /* @escapeNotVerified */ echo __('item')?><?php else:?> <?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?php /* @escapeNotVerified */ echo __('item')?><?php else:?><?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>