<?php
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>

<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <?php /** @var \Magento\Catalog\Model\Layer\Filter\Item $filterItem */ ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a class="filter-options-link" href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
                    <label class="tickbox" for="">
                        <input class="tickbox__field" type="checkbox" >
                    </label>
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?php /* @escapeNotVerified */ echo __('item')?><?php else:?> <?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?php /* @escapeNotVerified */ echo __('item')?><?php else:?><?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>

<script>
    jQuery(document).ready(function(){
        var filter = jQuery('.filter-options-link');

        filter.each(function(){
            var element = jQuery(this);
            var tickbox = element.find('.tickbox');

            element.click(function(){
                tickbox.toggleClass('tickbox--active');
            })
        })
    })
</script>