<?php
/**
 * integer_net Magento Module
 *
 * @category   IntegerNet
 * @package    IntegerNet_Solr
 * @copyright  Copyright (c) 2014-2017 integer_net GmbH (http://www.integer-net.de/)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 * @author     Fabian Schmengler <fs@integer-net.de>
 */
?>

<?php
/**
 * Autosuggest box template
 *
 * @see \IntegerNet\SolrSuggest\Implementor\AutosuggestBlock
 * @var $this \IntegerNet\SolrSuggest\Implementor\AutosuggestBlock
 */
?>

<?php if ($searchwordSuggestions = $this->getResult()->getSearchTermSuggestions()): ?>

    <ul class="integernet_solr-searchwords">

        <?php foreach ($searchwordSuggestions as $index => $item): ?>
            <li>
                <a href="<?php echo $item->getUrl() ?>"><?php echo $this->highlight($item->getTitle(), $this->getQuery()) ?></a>&hellip;
            </li>
        <?php endforeach ?>

    </ul>

<?php endif ?>

<?php $productSuggestions = $this->getResult()->getProductSuggestions() ?>
<?php if (sizeof($productSuggestions)): ?>

    <div class="integernet_solr-products-box">

        <h3>
            <strong><?php echo $this->__('Product Suggestions') ?></strong>
            <?php echo $this->__('for your Search') ?>
        </h3>

        <ul class="integernet_solr-products">

            <?php foreach ($productSuggestions as $index => $item): ?>
                <li>
                    <?php echo $this->highlight($item->getHtml(), $this->getQuery()) ?>
                </li>
            <?php endforeach ?>

            <li class="last"></li>
        </ul>
    </div>

<?php endif ?>


<?php $categorySuggestions = $this->getResult()->getCategorySuggestions() ?>
<?php $attributeSuggestions = $this->getResult()->getAttributeSuggestions() ?>
<?php $cmsPageSuggestions = $this->getResult()->getCmsPageSuggestions() ?>

<?php if (sizeof($categorySuggestions) || sizeof($cmsPageSuggestions) || sizeof($attributeSuggestions)): ?>

    <div class="integernet_solr-additional-box">
        <?php if (sizeof($categorySuggestions)): ?>

            <div class="integernet_solr-categories-box">

                <h3>
                    <strong><?php echo $this->__('Categories') ?></strong>
                    <?php echo $this->__('for your Search') ?>
                </h3>

                <ul class="integernet_solr-categories">

                    <?php foreach ($categorySuggestions as $index => $item): ?>
                        <li>
                            <a href="<?php echo $item->getUrl() ?>"><?php echo $this->highlight($item->getTitle(), $this->getQuery()) ?></a>
                        </li>
                    <?php endforeach ?>
                </ul>

            </div>
        <?php endif ?>

        <?php if (sizeof($cmsPageSuggestions)): ?>

            <div class="integernet_solr-cms-pages-box">
                <h3>
                    <strong><?php echo $this->__('Contents') ?></strong>
                    <?php echo $this->__('for your Search') ?>
                </h3>
                <ul class="integernet_solr-cms-pages">

                    <?php foreach ($cmsPageSuggestions as $index => $item): ?>
                        <li>
                            <a href="<?php echo $item->getUrl() ?>"><?php echo $this->highlight($item->getTitle(), $this->getQuery()) ?></a>
                        </li>
                    <?php endforeach ?>

                </ul>
            </div>

        <?php endif ?>

        <?php foreach($attributeSuggestions as $attributeSuggestion): ?>

            <div class="integernet_solr-attributes-box">

                <h3>
                    <strong><?php echo $attributeSuggestion->getLabel() ?></strong>
                </h3>

                <ul class="integernet_solr-attributes">
                    <li>
                        <?php $items = array() ?>
                        <?php foreach ($attributeSuggestion->getOptions() as $item): ?>
                            <?php $items[] = '<a href="' . htmlspecialchars($item->getUrl()) . '">' . $this->highlight($item->getTitle(), $this->getQuery()) . '</a>' ?>
                        <?php endforeach ?>
                        <?php echo implode(', ', $items) ?>
                    </li>
                </ul>
            </div>
        <?php endforeach ?>

        <div class="last"></div>
    </div>

<?php endif ?>

