<?php
/**
 * integer_net Magento Module
 *
 * @category   IntegerNet
 * @package    IntegerNet_Solr
 * @copyright  Copyright (c) 2014 integer_net GmbH (http://www.integer-net.de/)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */
/** @var Integer\Net\Solr\Block\Result\Layer\Checkbox $this */
?>
<?php if (!$this->getIsTopNav()): ?>
<input type="checkbox" name="" value="" <?php if ($this->getIsChecked()): ?>checked="checked"<?php endif ?> />
<?php endif ?>