<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getFlushUrl()?>')" type="button" class="scalable"><span><?php echo __('Rebuild Solr Autosuggest Cache') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo __('Cache for Solr autosuggest function. Contains configuration and template of autosuggest box.')?>
        </td>
    </tr>
</table>
